[project]
name = "eoread"
authors = [{name = "HYGEOS team"}]
description = "Modular implementation of satellite data input/output relying on xarray."
license = "Apache 2.0"
version = "0.5.0"
requires-python = "< 3.14"
readme = "README.md"
dependencies = [
    "lxml", "pyproj", "pysolar", "pyepr",
    "rioxarray", "h5netcdf", "h5py", "netcdf4"
]

[project.optional-dependencies]
git = [
    "core @ git+https://github.com/hygeos/core.git",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
eoread = { path = ".", editable = true, extras = ["git"]}
sand = { git = "git+https://github.com/hygeos/SAND.git" }

[tool.pixi.tasks]
tests = "pytest tests/"
reader = "python3 scripts/eval_readers.py"
docs-build = "quartodoc build --config docs/_quarto.yml"
docs-render = { cmd = "quarto render docs/", depends-on = ["docs-build"] }
docs-preview = { cmd = "quarto preview docs/", depends-on = ["docs-build"] }

[tool.pixi.dependencies]
pytest = "*"
pytest-html = "*"
pytest-xdist = "*"
matplotlib-base = "*"
ipykernel = "*"
libgdal-jp2openjpeg = "*"  # Required to read compress jp2 file in MSI reader
pyhdf = "*"
numba = "*"
quartodoc = "*"
nbformat = "*"
nbclient = "*"
jupyter-cache = "*"
griffe = ">=1.0,<2.0"

[tool.pixi.environments]
default = { features = ["hyp", "sys"], solve-group = "default" }

[tool.pixi.feature.sys.dependencies]
libgdal-jp2openjpeg = "*"

[tool.pixi.feature.hyp.dependencies]
xarray = "*"
dask = "*"
scipy = "*"
numpy = "*"
