[project]
name = "eoread"
version = "0.1.2"
description = "Modular and flexible implementation of satellite data input/output relying on xarray."

[tool.poetry.dependencies]
python = ">=3.6"
numpy = ">=1.19.1"
matplotlib = ">=3.3.1"
dask = {extras = ["array"], version = ">=2.24.0"}
shapely = ">=1.7.1"
scipy = ">=1.5.2"
netcdf4 = ">=1.5.4"
cdsapi = ">=0.3.0"
pyepr = ">=1.0.1"
pyproj = ">=2.6.1"
lxml = ">=4.5.2"
rasterio = ">=1.1.5"
h5netcdf = ">=0.8.1"
xarray = ">=0.16.0"

[tool.poetry.dev-dependencies]
pytest = ">=6.0.1"
pytest-html = ">=2.1.1"
pytest-xdist = ">=2.1.0"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
